image = "debian-cloud/debian-11"
subnet-name = ["managementsubnet" , "restrictedsubnet"]
subnet-cider = ["10.5.0.0/16" , "10.6.0.0/16"]
regions = "us-west1"
VM-name = "private-vm"
machine-type = "e2-micro"
zone = "us-west1-b"
service-name = "vm-service"
project-name = "ali-ali-378200"